/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.50
 * Generated at: 2021-09-16 02:13:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.lab2;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bai2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form action = \"bai2serlet\" method=\"post\" enctype=\"\">\r\n");
      out.write("	<label>Họ và tên</label>\r\n");
      out.write("	<input type=\"text\" name=\"username\" placeholder=\"Họ và tên\"><br>\r\n");
      out.write("	\r\n");
      out.write("	<label>Ngày sinh</label>\r\n");
      out.write("	<input type=\"date\" id=\"birthday\" name=\"birthday\"><br>\r\n");
      out.write("	\r\n");
      out.write("	<label>Giới tính</label>\r\n");
      out.write("	<input type=\"radio\" name=\"sex\" value=\"Male\">Nam\r\n");
      out.write("	<input type=\"radio\" name=\"sex\" value=\"Female\">Nữ<br>\r\n");
      out.write("	\r\n");
      out.write("	<label>TT hôn nhân</label><input type=\"checkbox\" name=\"check\" value=\"Đã có gia đình\">Đã có gia đình chưa ?<br>\r\n");
      out.write("	\r\n");
      out.write("	<label>Quốc tịnh</label>\r\n");
      out.write("	<input list=\"nationality\" name=\"nationality\"><br>\r\n");
      out.write("		<datalist id =\"nationality\">\r\n");
      out.write("			<option value=\"Việt nam\">\r\n");
      out.write("			<option value=\"Trung quốc\">\r\n");
      out.write("			<option value=\"Ấn độ\">\r\n");
      out.write("			<option value=\"Nga\">\r\n");
      out.write("			<option value=\"Mỹ\">\r\n");
      out.write("		</datalist>\r\n");
      out.write("		\r\n");
      out.write("	<label>Sở thích</label>\r\n");
      out.write("	<input type=\"checkbox\" name=\"hobby\" value=\"Read book\"><lable for=\"favorite1\">Read book</lable>\r\n");
      out.write("	<input type=\"checkbox\" name=\"hobby\" value=\"Travel\"><lable for=\"favorite2\">Travel</lable>\r\n");
      out.write("	<input type=\"checkbox\" name=\"hobby\" value=\"Listen to music\"><lable for=\"favorite3\">Listen to music</lable>\r\n");
      out.write("	<input type=\"checkbox\" name=\"hobby\" value=\"Different\"><lable for=\"favorite4\">Different</lable><br>\r\n");
      out.write("	\r\n");
      out.write("	<label>Ghi chú</label>\r\n");
      out.write("	<textarea name=\"message\" rows=\"10\" cols=\"30\">Oke</textarea><br>\r\n");
      out.write("	\r\n");
      out.write("	<hr>\r\n");
      out.write("	\r\n");
      out.write("	<input type=\"submit\" name=\"submit\" value=\"Đăng ký\">\r\n");
      out.write("	\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
