/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.50
 * Generated at: 2022-03-24 13:19:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("	<meta name=\"author\" content=\"Untree.co\">\r\n");
      out.write("	<link rel=\"shortcut icon\" href=\"../favicon.png\">\r\n");
      out.write("	<meta name=\"description\" content=\"\" />\r\n");
      out.write("	<meta name=\"keywords\" content=\"bootstrap, bootstrap5\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/font/fontawesome/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap/tiny-slider.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/footer.css\" rel=\"stylesheet\">\r\n");
      out.write("<title>Furni</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Start Footer Section -->\r\n");
      out.write("	<footer class=\"footer-section\">\r\n");
      out.write("		<div class=\"container relative\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"sofa-img\">\r\n");
      out.write("				<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/sofa.png\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-8\">\r\n");
      out.write("					<div class=\"subscription-form\">\r\n");
      out.write("						<h3 class=\"d-flex align-items-center\">\r\n");
      out.write("							<span class=\"me-1\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/envelope-outline.svg\"\r\n");
      out.write("								alt=\"Image\" class=\"img-fluid\"></span><span>Subscribe to\r\n");
      out.write("								Newsletter</span>\r\n");
      out.write("						</h3>\r\n");
      out.write("\r\n");
      out.write("						<form action=\"#\" class=\"row g-3\">\r\n");
      out.write("							<div class=\"col-auto\">\r\n");
      out.write("								<input type=\"text\" class=\"form-control\"\r\n");
      out.write("									placeholder=\"Enter your name\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-auto\">\r\n");
      out.write("								<input type=\"email\" class=\"form-control\"\r\n");
      out.write("									placeholder=\"Enter your email\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-auto\">\r\n");
      out.write("								<button class=\"btn btn-primary\">\r\n");
      out.write("									<span class=\"fa fa-paper-plane\"></span>\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</form>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"row g-5 mb-5\">\r\n");
      out.write("				<div class=\"col-lg-4\">\r\n");
      out.write("					<div class=\"mb-4 footer-logo-wrap\">\r\n");
      out.write("						<a href=\"#\" class=\"footer-logo\">Furni<span>.</span></a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<p class=\"mb-4\">Donec facilisis quam ut purus rutrum lobortis.\r\n");
      out.write("						Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet\r\n");
      out.write("						velit. Aliquam vulputate velit imperdiet dolor tempor tristique.\r\n");
      out.write("						Pellentesque habitant</p>\r\n");
      out.write("\r\n");
      out.write("					<ul class=\"list-unstyled custom-social\">\r\n");
      out.write("						<li><a href=\"#\"><i class=\"fa fa-brands fa-facebook\"></i></a></li>\r\n");
      out.write("						<li><a href=\"#\"><i class=\"fa fa-brands fa-twitter\"></i></a></li>\r\n");
      out.write("						<li><a href=\"#\"><i class=\"fa fa-brands fa-instagram\"></i></a></li>\r\n");
      out.write("						<li><a href=\"#\"><i class=\"fa fa-brands fa-linkedin\"></i></a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-8\">\r\n");
      out.write("					<div class=\"row links-wrap\">\r\n");
      out.write("						<div class=\"col-6 col-sm-6 col-md-3\">\r\n");
      out.write("							<ul class=\"list-unstyled\">\r\n");
      out.write("								<li><a href=\"#\">About us</a></li>\r\n");
      out.write("								<li><a href=\"#\">Services</a></li>\r\n");
      out.write("								<li><a href=\"#\">Blog</a></li>\r\n");
      out.write("								<li><a href=\"#\">Contact us</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-6 col-sm-6 col-md-3\">\r\n");
      out.write("							<ul class=\"list-unstyled\">\r\n");
      out.write("								<li><a href=\"#\">Support</a></li>\r\n");
      out.write("								<li><a href=\"#\">Knowledge base</a></li>\r\n");
      out.write("								<li><a href=\"#\">Live chat</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-6 col-sm-6 col-md-3\">\r\n");
      out.write("							<ul class=\"list-unstyled\">\r\n");
      out.write("								<li><a href=\"#\">Jobs</a></li>\r\n");
      out.write("								<li><a href=\"#\">Our team</a></li>\r\n");
      out.write("								<li><a href=\"#\">Leadership</a></li>\r\n");
      out.write("								<li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-6 col-sm-6 col-md-3\">\r\n");
      out.write("							<ul class=\"list-unstyled\">\r\n");
      out.write("								<li><a href=\"#\">Nordic Chair</a></li>\r\n");
      out.write("								<li><a href=\"#\">Kruzo Aero</a></li>\r\n");
      out.write("								<li><a href=\"#\">Ergonomic Chair</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"border-top copyright\">\r\n");
      out.write("				<div class=\"row pt-4\">\r\n");
      out.write("					<div class=\"col-lg-6\">\r\n");
      out.write("						<p class=\"mb-2 text-center text-lg-start\">\r\n");
      out.write("							Copyright &copy;\r\n");
      out.write("							<script>\r\n");
      out.write("								document.write(new Date().getFullYear());\r\n");
      out.write("							</script>\r\n");
      out.write("							. All Rights Reserved. &mdash; Designed with love by <a\r\n");
      out.write("								href=\"https://untree.co\" target=\"_blank\" rel=\"nofollow noopener\">Untree.co</a>\r\n");
      out.write("							&bullet; <a href=\"https://untree.co/license\" target=\"_blank\"\r\n");
      out.write("								rel=\"nofollow noopener\">License</a>\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"col-lg-6 text-center text-lg-end\">\r\n");
      out.write("						<ul class=\"list-unstyled d-inline-flex ms-auto\">\r\n");
      out.write("							<li class=\"me-4\"><a href=\"#\">Terms &amp; Conditions</a></li>\r\n");
      out.write("							<li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("	<!-- End Footer Section -->\r\n");
      out.write("\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/tiny-slider.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/custom.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
