/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.50
 * Generated at: 2022-03-24 13:19:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta name=\"author\" content=\"Untree.co\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/favicon.png\">\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"bootstrap, bootstrap5\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/index.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/font/fontawesome/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bootstrap/tiny-slider.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Furni</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "view/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Start Product Section -->\r\n");
      out.write("	<div class=\"product-section\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-md-12 col-lg-3 mb-5 mb-lg-0\">\r\n");
      out.write("					<h2 class=\"mb-4 section-title\">Crafted with excellent\r\n");
      out.write("						material.</h2>\r\n");
      out.write("					<p class=\"mb-4\">Donec vitae odio quis nisl dapibus malesuada.\r\n");
      out.write("						Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor\r\n");
      out.write("						tempor tristique.</p>\r\n");
      out.write("					<p class=\"btn-md-centrer\">\r\n");
      out.write("						<a href=\"shop.html\" class=\"btn\">Explore</a>\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12 col-md-4 col-lg-3 mb-5 mb-md-0\">\r\n");
      out.write("					<a class=\"product-item\" href=\"cart.html\"> <img\r\n");
      out.write("						src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/product-1.png\" class=\"img-fluid product-thumbnail\">\r\n");
      out.write("						<h3 class=\"product-title\">Nordic Chair</h3> <strong\r\n");
      out.write("						class=\"product-price\">$50.00</strong> <span class=\"icon-cross\">\r\n");
      out.write("							<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/cross.svg\" class=\"img-fluid\">\r\n");
      out.write("					</span>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12 col-md-4 col-lg-3 mb-5 mb-md-0\">\r\n");
      out.write("					<a class=\"product-item\" href=\"cart.html\"> <img\r\n");
      out.write("						src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/product-2.png\" class=\"img-fluid product-thumbnail\">\r\n");
      out.write("						<h3 class=\"product-title\">Kruzo Aero Chair</h3> <strong\r\n");
      out.write("						class=\"product-price\">$78.00</strong> <span class=\"icon-cross\">\r\n");
      out.write("							<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/cross.svg\" class=\"img-fluid\">\r\n");
      out.write("					</span>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12 col-md-4 col-lg-3 mb-5 mb-md-0\">\r\n");
      out.write("					<a class=\"product-item\" href=\"cart.html\"> <img\r\n");
      out.write("						src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/product-3.png\" class=\"img-fluid product-thumbnail\">\r\n");
      out.write("						<h3 class=\"product-title\">Ergonomic Chair</h3> <strong\r\n");
      out.write("						class=\"product-price\">$43.00</strong> <span class=\"icon-cross\">\r\n");
      out.write("							<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/cross.svg\" class=\"img-fluid\">\r\n");
      out.write("					</span>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- End Product Section -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Start Why Choose Us Section -->\r\n");
      out.write("	<div class=\"why-choose-section\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row justify-content-between\">\r\n");
      out.write("				<div class=\"col-lg-6\">\r\n");
      out.write("					<h2 class=\"section-title\">Why Choose Us</h2>\r\n");
      out.write("					<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac\r\n");
      out.write("						aliquet velit. Aliquam vulputate velit imperdiet dolor tempor\r\n");
      out.write("						tristique.</p>\r\n");
      out.write("					<div class=\"row my-5\">\r\n");
      out.write("						<div class=\"col-6 col-md-6\">\r\n");
      out.write("							<div class=\"feature\">\r\n");
      out.write("								<div class=\"icon\">\r\n");
      out.write("									<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/truck.svg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<h3>Fast &amp; Free Shipping</h3>\r\n");
      out.write("								<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac\r\n");
      out.write("									aliquet velit. Aliquam vulputate.</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-6 col-md-6\">\r\n");
      out.write("							<div class=\"feature\">\r\n");
      out.write("								<div class=\"icon\">\r\n");
      out.write("									<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/bag.svg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<h3>Easy to Shop</h3>\r\n");
      out.write("								<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac\r\n");
      out.write("									aliquet velit. Aliquam vulputate.</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-6 col-md-6\">\r\n");
      out.write("							<div class=\"feature\">\r\n");
      out.write("								<div class=\"icon\">\r\n");
      out.write("									<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/support.svg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<h3>24/7 Support</h3>\r\n");
      out.write("								<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac\r\n");
      out.write("									aliquet velit. Aliquam vulputate.</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-6 col-md-6\">\r\n");
      out.write("							<div class=\"feature\">\r\n");
      out.write("								<div class=\"icon\">\r\n");
      out.write("									<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/return.svg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<h3>Hassle Free Returns</h3>\r\n");
      out.write("								<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac\r\n");
      out.write("									aliquet velit. Aliquam vulputate.</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-5 img-full\">\r\n");
      out.write("					<div class=\"img-wrap \">\r\n");
      out.write("						<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/why-choose-us-img.jpg\" alt=\"Image\"\r\n");
      out.write("							class=\"img-fluid\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- End Why Choose Us Section -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Start We Help Section -->\r\n");
      out.write("	<div class=\"we-help-section\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row justify-content-between\">\r\n");
      out.write("				<div class=\"col-lg-7 mb-5 mb-lg-0 img-full\">\r\n");
      out.write("					<div class=\"imgs-grid\">\r\n");
      out.write("						<div class=\"grid grid-1\">\r\n");
      out.write("							<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/img-grid-1.jpg\" alt=\"Untree.co\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"grid grid-2\">\r\n");
      out.write("							<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/img-grid-2.jpg\" alt=\"Untree.co\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"grid grid-3\">\r\n");
      out.write("							<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/img-grid-3.jpg\" alt=\"Untree.co\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-5 ps-lg-5\">\r\n");
      out.write("					<h2 class=\"section-title mb-4\">We Help You Make Modern\r\n");
      out.write("						Interior Design</h2>\r\n");
      out.write("					<p>Donec facilisis quam ut purus rutrum lobortis. Donec vitae\r\n");
      out.write("						odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam\r\n");
      out.write("						vulputate velit imperdiet dolor tempor tristique. Pellentesque\r\n");
      out.write("						habitant morbi tristique senectus et netus et malesuada</p>\r\n");
      out.write("\r\n");
      out.write("					<ul class=\"list-unstyled custom-list my-4\">\r\n");
      out.write("						<li>Donec vitae odio quis nisl dapibus malesuada</li>\r\n");
      out.write("						<li>Donec vitae odio quis nisl dapibus malesuada</li>\r\n");
      out.write("						<li>Donec vitae odio quis nisl dapibus malesuada</li>\r\n");
      out.write("						<li>Donec vitae odio quis nisl dapibus malesuada</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<p class=\"btn-md-centrer\">\r\n");
      out.write("						<a herf=\"#\" class=\"btn\">Explore</a>\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- End We Help Section -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Start Popular Product -->\r\n");
      out.write("	<div class=\"popular-product\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-12 col-md-6 col-lg-4 mb-4 mb-lg-0\">\r\n");
      out.write("					<div class=\"product-item-sm d-flex\">\r\n");
      out.write("						<div class=\"thumbnail\">\r\n");
      out.write("							<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/product-1.png\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"pt-3\">\r\n");
      out.write("							<h3>Nordic Chair</h3>\r\n");
      out.write("							<p>Donec facilisis quam ut purus rutrum lobortis. Donec vitae\r\n");
      out.write("								odio</p>\r\n");
      out.write("							<p>\r\n");
      out.write("								<a href=\"#\">Read More</a>\r\n");
      out.write("							</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12 col-md-6 col-lg-4 mb-4 mb-lg-0\">\r\n");
      out.write("					<div class=\"product-item-sm d-flex\">\r\n");
      out.write("						<div class=\"thumbnail\">\r\n");
      out.write("							<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/product-2.png\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"pt-3\">\r\n");
      out.write("							<h3>Kruzo Aero Chair</h3>\r\n");
      out.write("							<p>Donec facilisis quam ut purus rutrum lobortis. Donec vitae\r\n");
      out.write("								odio</p>\r\n");
      out.write("							<p>\r\n");
      out.write("								<a href=\"#\">Read More</a>\r\n");
      out.write("							</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12 col-md-6 col-lg-4 mb-4 mb-lg-0\">\r\n");
      out.write("					<div class=\"product-item-sm d-flex\">\r\n");
      out.write("						<div class=\"thumbnail\">\r\n");
      out.write("							<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/product-3.png\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"pt-3\">\r\n");
      out.write("							<h3>Ergonomic Chair</h3>\r\n");
      out.write("							<p>Donec facilisis quam ut purus rutrum lobortis. Donec vitae\r\n");
      out.write("								odio</p>\r\n");
      out.write("							<p>\r\n");
      out.write("								<a href=\"#\">Read More</a>\r\n");
      out.write("							</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- End Popular Product -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Start Testimonial Slider -->\r\n");
      out.write("	<div class=\"testimonial-section\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-7 mx-auto text-center\">\r\n");
      out.write("					<h2 class=\"section-title\">Testimonials</h2>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row justify-content-center\">\r\n");
      out.write("				<div class=\"col-lg-12\">\r\n");
      out.write("					<div class=\"testimonial-slider-wrap text-center\">\r\n");
      out.write("						<div id=\"testimonial-nav\">\r\n");
      out.write("							<span class=\"prev\" data-controls=\"prev\"><span\r\n");
      out.write("								class=\"fa fa-chevron-left\"></span></span> <span class=\"next\"\r\n");
      out.write("								data-controls=\"next\"><span class=\"fa fa-chevron-right\"></span></span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"testimonial-slider\">\r\n");
      out.write("							<div class=\"item\">\r\n");
      out.write("								<div class=\"row justify-content-center\">\r\n");
      out.write("									<div class=\"col-lg-8 mx-auto\">\r\n");
      out.write("										<div class=\"testimonial-block text-center\">\r\n");
      out.write("											<blockquote class=\"mb-5\">\r\n");
      out.write("												<p>&ldquo;Donec facilisis quam ut purus rutrum lobortis.\r\n");
      out.write("													Donec vitae odio quis nisl dapibus malesuada. Nullam ac\r\n");
      out.write("													aliquet velit. Aliquam vulputate velit imperdiet dolor\r\n");
      out.write("													tempor tristique. Pellentesque habitant morbi tristique\r\n");
      out.write("													senectus et netus et malesuada fames ac turpis egestas.\r\n");
      out.write("													Integer convallis volutpat dui quis scelerisque.&rdquo;</p>\r\n");
      out.write("											</blockquote>\r\n");
      out.write("											<div class=\"author-info\">\r\n");
      out.write("												<div class=\"author-pic\">\r\n");
      out.write("													<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/avatar.jpg\" alt=\"Hoàng Tôn\"\r\n");
      out.write("														class=\"img-fluid\">\r\n");
      out.write("												</div>\r\n");
      out.write("												<h3 class=\"font-weight-bold\">Hoàng Tôn</h3>\r\n");
      out.write("												<span class=\"position d-block mb-3\">CEO, Co-Founder,\r\n");
      out.write("													XYZ Inc.</span>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- END item -->\r\n");
      out.write("							<div class=\"item\">\r\n");
      out.write("								<div class=\"row justify-content-center\">\r\n");
      out.write("									<div class=\"col-lg-8 mx-auto\">\r\n");
      out.write("										<div class=\"testimonial-block text-center\">\r\n");
      out.write("											<blockquote class=\"mb-5\">\r\n");
      out.write("												<p>&ldquo;Donec facilisis quam ut purus rutrum lobortis.\r\n");
      out.write("													Donec vitae odio quis nisl dapibus malesuada. Nullam ac\r\n");
      out.write("													aliquet velit. Aliquam vulputate velit imperdiet dolor\r\n");
      out.write("													tempor tristique. Pellentesque habitant morbi tristique\r\n");
      out.write("													senectus et netus et malesuada fames ac turpis egestas.\r\n");
      out.write("													Integer convallis volutpat dui quis scelerisque.&rdquo;</p>\r\n");
      out.write("											</blockquote>\r\n");
      out.write("											<div class=\"author-info\">\r\n");
      out.write("												<div class=\"author-pic\">\r\n");
      out.write("													<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/avatar.jpg\" alt=\"Hoàng Tôn\"\r\n");
      out.write("														class=\"img-fluid\">\r\n");
      out.write("												</div>\r\n");
      out.write("												<h3 class=\"font-weight-bold\">Hoàng Tôn</h3>\r\n");
      out.write("												<span class=\"position d-block mb-3\">CEO, Co-Founder,\r\n");
      out.write("													XYZ Inc.</span>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- END item -->\r\n");
      out.write("							<div class=\"item\">\r\n");
      out.write("								<div class=\"row justify-content-center\">\r\n");
      out.write("									<div class=\"col-lg-8 mx-auto\">\r\n");
      out.write("										<div class=\"testimonial-block text-center\">\r\n");
      out.write("											<blockquote class=\"mb-5\">\r\n");
      out.write("												<p>&ldquo;Donec facilisis quam ut purus rutrum lobortis.\r\n");
      out.write("													Donec vitae odio quis nisl dapibus malesuada. Nullam ac\r\n");
      out.write("													aliquet velit. Aliquam vulputate velit imperdiet dolor\r\n");
      out.write("													tempor tristique. Pellentesque habitant morbi tristique\r\n");
      out.write("													senectus et netus et malesuada fames ac turpis egestas.\r\n");
      out.write("													Integer convallis volutpat dui quis scelerisque.&rdquo;</p>\r\n");
      out.write("											</blockquote>\r\n");
      out.write("\r\n");
      out.write("											<div class=\"author-info\">\r\n");
      out.write("												<div class=\"author-pic\">\r\n");
      out.write("													<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/avatar.jpg\" alt=\"Hoàng Tôn\"\r\n");
      out.write("														class=\"img-fluid\">\r\n");
      out.write("												</div>\r\n");
      out.write("												<h3 class=\"font-weight-bold\">Hoàng Tôn</h3>\r\n");
      out.write("												<span class=\"position d-block mb-3\">CEO, Co-Founder,\r\n");
      out.write("													XYZ Inc.</span>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- END item -->\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- End Testimonial Slider -->\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "view/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/tiny-slider.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/custom.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
